name: Тесты и раскатка на Pull Request (остановка)

on:
  pull_request:
    types: [closed]

jobs:
  stop-deployment-dev:
    name: Deploy Development (stop)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Stop deployment
        run: |
          curl -X 'POST' \
            'https://ci.dev.profcomff.com/pr_stop' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: ${{ secrets.CI_DYAKOVSPACE_MSK_TOKEN }}' \
            -d '{
              "repo_url": "${{ github.repository }}",
              "git_ref": "${{ github.ref }}"
            }'

      - uses: avakar/set-deployment-status@v1
        with:
          state: inactive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
